### ISSUE TITLE
In my project i was using C++14 level features.

### ISSUE THREAD

**Issue by mdsitton** [FretStorm/FretStorm#3]
Any objections about enabling it here?

**Comment by Salamandar** [comment]
I agree with you, in fact i'm already using it ;)

**Comment by mdsitton** [comment]
I was glanceing through the CmakeLists.txt and you only have 11 set. I guess i'll fix that lol

**Comment by Salamandar** [comment]
Oh yeah, I missread your comment ^^
I never used C++14 features, but no objections !

**Comment by mdsitton** [comment]
Would totally be pushing stuff already if github wast basically revoking my windows ssh keys....

**Comment by mdsitton** [comment]
If i cant get it to work soon linux it is lol

**Comment by Salamandar** [comment]
Well you can push to github with login/password too :)

**Comment by mdsitton** [comment]
i got it figured out.
