### ISSUE TITLE
header files.

### ISSUE THREAD

**Issue by mdsitton** [FretStorm/FretStorm#4]
Something to mention can we make the header files extensions be .hpp. Generally i just prefer that, and another thing my editor only does C syntax highlighting on .h files so some keywords are in general missing.

**Comment by Salamandar** [comment]
I dont see any problem to that. In fact I don't write C++ for a long time, and I was never sure to use .h or .hpp ^^

**Comment by Salamandar** [comment]
Would need some refactoring for the includes though ^^
BTW what's your editor ? Mine is SublimeText3.

**Comment by mdsitton** [comment]
I generally use a combo of SublimeText or Atom. Just depends really.
